### ISSUE TITLE
ideas from lab meeting

### ISSUE THREAD

**Issue by kushalkolar** [hantman-lab/animal-soup#2]
* Use only 1 or a few seconds after cue to not train on false-negatives of pre-cue lift, and the spurious supinates, hand on table etc.

**Comment by clewis7** [comment]
- only use control trials

**Comment by kushalkolar** [comment]
Now that you're cleaning stuff and have seen many ethograms, what do you think about using just the period from the beginning until a few seconds after chew (when it is a success trial). Or do you think we should still train on the entire video because there is useful stuff that happens?

**Comment by clewis7** [comment]
I think on a success trial that would be fine, but on other trials I think it is useful to have the whole video being annotated because useful stuff happens there...so I'm not sure at that point if we should just train on all videos regardless of success/failure

**Comment by clewis7** [comment]
I think after I clean them and all of the ethograms do not have the pre-cue lift and post-chew supinate, etc. that it would be okay to train on the whole video
