### ISSUE TITLE
Removing mescore as a dependency

### ISSUE THREAD

**Issue by clewis7** [hantman-lab/animal-soup#20]
Need to remove mescore as a dependency, only using it for LazyVideo implementation 

is there something else that can be used? or simply move code to this repo?

Current problem: decord does not look like it is being maintained, should we continue to use?

**Comment by kushalkolar** [comment]
I would just implement a single `LazyVideo` class here (no base class, just get all the methods and properties). It should be fairly easy to dropin a backend-replacement for `decord` if we come across one!

**Comment by clewis7** [comment]
closed in #21, will update LazyVideo to single class in #18
