### ISSUE TITLE
storing outputs?

### ISSUE THREAD

**Issue by clewis7** [hantman-lab/animal-soup#29]
current:
- if `model_out` is not provided, then empty folder is made to place logs, checkpoints, and eventually and hdf5 file of ouputs 
- if `model_out` is given, then it should be an empty directory for the same things listed above

problems with this: retraining, the tensorboard log keeps track of the "experiment version" or how many times train has been called on the current dataframe

what is the best way to keep track of things if potential retraining will happen?

**Comment by kushalkolar** [comment]
make `model_out` mandatory?
