### ISSUE TITLE
separating pez and table

### ISSUE THREAD

**Issue by clewis7** [hantman-lab/animal-soup#31]
predictions for pez using model that only had table data did not yield good results, will need to have a separate ground truth for pez 

runs into the problem that then you can only have one type of experiment in each dataframe (don't think this will be a problem on the user end, but will need to be enforced on the back end)

initial thought is to "set" the experiment type for a dataframe and only that experiment type can be added 

then, when you call a df extension to train or infer it will use the model checkpoint default for the type of experiment

**Comment by clewis7** [comment]
add attribute exp_type to a dataframe

**Comment by kushalkolar** [comment]
yea I would allow adding any experiment type (`table`, `pez`, etc.) to a dataframe, but when they use `train()` or `infer()` they can specify models specific to the exp type.
